version: '2'
services:
  db:  
    image: mysql:5.7
    networks:
      - wordpress-network
    environment: 
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    image:wordpress:latest
    networks: 
      -wordpress-network
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wordpress
    restart: always

networks: 
  wordpress-network:
    driver:bridge