version: '2'

services:
  jenkins:
    build: 
       context: .
       dockerfile: jenkins.dockerfile
    ports: 
      - "8081:8080"    
    networks:
       - jenkins
  
networks:
  jenkins:
    driver: bridge
